application: simplebills-153311
module: default
version: alpha-003
runtime: python27
api_version: 1
threadsafe: true
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 3

handlers:
- url: /_ah/spi/.*
  script: api.api
  secure: always


libraries:
- name: endpoints
  version: latest

- name: pycrypto
  version: latest

- name: MySQLdb
  version: "latest"

env_variables:
  WEB_CLIENT_ID: '108166075039-bm76la2ddhbbv775unf3qen60s6qqv4c.apps.googleusercontent.com'
  WEB_CLIENT_SECRET: 'KOC1rulqiSyczakIrW3TZyCt'
  FILE_BUCKET: 'simplebills-153311.appspot.com'
  STAGING_FILE_BUCKET: 'staging.simplebills-153311.appspot.com'
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://root:@127.0.0.1:3306/simple_bills?charset=utf8'

