application: simplebills-152707
module: web
version: alpha-002
runtime: python27
api_version: 1
threadsafe: true
basic_scaling:
  idle_timeout: 10m
  max_instances: 1

handlers:
- url: /static/css
  static_dir: static/css

- url: /static/js
  static_dir: static/js

- url: /static/images
  static_dir: static/images

- url: /
  script: main.app

- url: /.+
  script: main.app


libraries:

- name: pycrypto
  version: latest

- name: jinja2
  version: latest

env_variables:
  CRUDAPI_SERVER: 'http://localhost:8080'
  OAUTH_REDIRECT_PATH: '/oauth2callback'
  API_ROOT_PATH: '/_ah/api'
  FILE_BUCKET: 'simplebills'
  STAGING_FILE_BUCKET: 'simplebills-file-staging-bucket'
  WEB_CLIENT_ID: '601259546874-04vgln5ohv19gp8dq8mbnu18rfnuo5dl.apps.googleusercontent.com'
  WEB_CLIENT_SECRET: 'N0xjMEWPfjcGCkxfXlqIAYRS'
