application: simplebills
version: alpha-001
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/spi/.*
  script: api.api
  secure: always

- url: /
  script: main.app

- url: /.+
  script: main.app

libraries:
- name: endpoints
  version: latest

- name: pycrypto
  version: latest
