application: simplebills-153311
module: www
version: www-alpha-005
runtime: python27
api_version: 1
threadsafe: true
basic_scaling:
  idle_timeout: 10m
  max_instances: 2

handlers:
- url: /static/css
  static_dir: static/css

- url: /static/js
  static_dir: static/js

- url: /static/images
  static_dir: static/images

- url: /
  script: main.app

- url: /.+
  script: main.app


libraries:

- name: pycrypto
  version: latest

- name: jinja2
  version: latest

env_variables:
  CRUDAPI_SERVER: 'http://localhost:8080'
  OAUTH_REDIRECT_PATH: '/oauth2callback'
  API_ROOT_PATH: '/_ah/api'
  FILE_BUCKET: 'simplebills-153311.appspot.com'
  STAGING_FILE_BUCKET: 'staging.simplebills-153311.appspot.com'
  WEB_CLIENT_ID: '108166075039-bm76la2ddhbbv775unf3qen60s6qqv4c.apps.googleusercontent.com'
  WEB_CLIENT_SECRET: 'KOC1rulqiSyczakIrW3TZyCt'
